### ISSUE TITLE
Add SFTP service to basehub

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/features#20]
This service, which ships with the [yuvipanda/jupyterhub-ssh helm chart](https://github.com/yuvipanda/jupyterhub-ssh), is used to bring data in and out of home directories and works without involvement from a user server by having an SFTP server mount the user storage's directly.

The `jupyterhub-ssh` chart also provides another kind of service - to start or access already started user servers via `ssh`. Setup of that is not part of this issue - only the `sftp` server.

### Action point

- [ ] Find agreement to work towards adding this to basehub - use :+1: or comment why not
- [ ] Upstream relevant chore maintenance
  - [ ] Update the [helm chart schema](https://github.com/yuvipanda/jupyterhub-ssh/blob/main/helm-chart/jupyterhub-ssh/schema.yaml) so that it captures the [possible chart values](https://github.com/yuvipanda/jupyterhub-ssh/blob/main/helm-chart/jupyterhub-ssh/values.yaml) for use of `sftp` to help us not make mistakes.
- [ ] Add an opt-in dependency on the helm chart and trial it
  See technical notes for an example of what this can involve, as examplified with configuration from the JMTE deployment I've managed.
- Write documentation
  - [ ] User facing docs
  - [ ] Engineer facing docs
- Followup by reopening closed support tickets
  - [ ] Freshdesk ticket [447](https://2i2c.freshdesk.com/a/tickets/447)

### Technical notes

This ought to be an opt-in feature not enabled by default initially.

Below are snippets of config from configuring jupyterhub-ssh (both ssh part and sftp part) for hub.jupytearth.org also referred to as the JMTE project, as seen in changes in 2i2c-org/infrastructure#436. There, jupyterhub-ssh was added as a dependency to the daskhub helm chart.

From [config/clusters/jmte/common.values.yaml](https://github.com/2i2c-org/infrastructure/pull/436/files#diff-91aa1f4385c492c4adba448b741048dfa33db48b2468807638d7627fd97b7cd3R415-R429)

```yaml
basehub:
  jupyterhub:
    proxy:
      service:
        # jupyterhub-ssh/sftp integration part 1/3:
        #
        # We must accept traffic to the k8s Service (proxy-public) receiving traffic
        # from the internet. Port 22 is typically used for both SSH and SFTP, but we
        # can't use the same port for both so we use 2222 for SFTP in this example.
        #
        extraPorts:
          - name: ssh
            port: 22
            targetPort: ssh
          - name: sftp
            port: 2222
            targetPort: sftp
      traefik:
        # jupyterhub-ssh/sftp integration part 2/3:
        #
        # We must accept traffic arriving to the autohttps pod (traefik) from the
        # proxy-public service. Expose a port and update the NetworkPolicy
        # to tolerate incoming (ingress) traffic on the exposed port.
        #
        extraPorts:
          - name: ssh
            containerPort: 8022
          - name: sftp
            containerPort: 2222
        networkPolicy:
          allowedIngressPorts: [http, https, ssh, sftp]
        # jupyterhub-ssh/sftp integration part 3/3:
        #
        # extraStaticConfig is adjusted by staging/prod values
        # extraDynamicConfig is adjusted by staging/prod values



# jupyterhub-ssh values.yaml reference:
# https://github.com/yuvipanda/jupyterhub-ssh/blob/main/helm-chart/jupyterhub-ssh/values.yaml
#
jupyterhub-ssh:
  hubUrl: http://proxy-http:8000

  ssh:
    enabled: true

  sftp:
    # enabled is adjusted by staging/prod values
    # enabled: true
    pvc:
      enabled: true
      name: home-nfs
```

From [`config/clusters/jmte/prod.values.yaml`](https://github.com/2i2c-org/infrastructure/pull/436/files#diff-5b8083e9d5a4470fb47466d0a15e9970537cd6be29a3e3547fe23b6677bd129fR85-R117):

```yaml
basehub:
  jupyterhub:
    proxy:
      traefik:
        # jupyterhub-ssh/sftp integration part 3/3:
        #
        # We must let traefik know it should listen for traffic (traefik entrypoint)
        # and route it (traefik router) onwards to the jupyterhub-ssh k8s Service
        # (traefik service).
        #
        extraStaticConfig:
          entryPoints:
            ssh-entrypoint:
              address: :8022
            sftp-entrypoint:
              address: :2222
        extraDynamicConfig:
          tcp:
            services:
              ssh-service:
                loadBalancer:
                  servers:
                    - address: jupyterhub-ssh:22
              sftp-service:
                loadBalancer:
                  servers:
                    - address: jupyterhub-sftp:22
            routers:
              ssh-router:
                entrypoints: [ssh-entrypoint]
                rule: HostSNI(`*`)
                service: ssh-service
              sftp-router:
                entrypoints: [sftp-entrypoint]
                rule: HostSNI(`*`)
                service: sftp-service



jupyterhub-ssh:
  sftp:
    enabled: true
```

From [helm-charts/daskhub/Chart.yaml](https://github.com/2i2c-org/infrastructure/pull/436/files#diff-e1fe65e540a5c5e574f2ba7beb56d43bb0d99e80e59f0988067b18bc5d367e9dR16-R18):

```yaml
  - name: jupyterhub-ssh
    version: 0.0.1-n142.h402a3d6
    repository: https://yuvipanda.github.io/jupyterhub-ssh/
```

From [helm-charts/daskhub/values.schema.yaml](https://github.com/2i2c-org/infrastructure/pull/436/files#diff-fcfb59dbcc58f20d0f264a97b1239e1693a6319956775b07238e164ac92d02aaR30-R35):

```yaml
  # jupyterhub-ssh is a dependent helm chart, we rely on its schema validation
  # for values passed to it and are not imposing restrictions on them in this
  # helm chart.
  jupyterhub-ssh:
    type: object
    additionalProperties: true
```
