### ISSUE TITLE
Document how to make a maintenance announcement

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/features#24]
If a maintenance timeframe has been planned with a community representative, it can be announced using configuration like below, which would be good to have documented somewhere.

@pnasrat proposed that it could be documentation we put `maybe under SRE Guilde>Support Tasks or How-to to set maintenance announcements [...]`

```yaml
basehub:
  jupyterhub:
    hub:
      config:
        JupyterHub:
          # Announcement is a JupyterHub feature to present messages to users in
          # web pages under the /hub path (JupyterHub responds), but not via the
          # /user path (single-user server responds).
          #
          # ref: https://github.com/2i2c-org/infrastructure/issues/1501
          # ref: https://jupyterhub.readthedocs.io/en/stable/reference/templates.html#announcement-configuration-variables
          #
          template_vars:
            announcement: >-
              <strong>
              Service maintenance is scheduled Sunday March 19, to Monday 8AM
              EST.
              </strong>
              <br/>
              Running servers may be forcefully stopped and service disruption
              is expected.
```

### Related

- 2i2c-org/infrastructure#1501
- 2i2c-org/infrastructure#2363
