### ISSUE TITLE
How to customize a JupyterHub and BinderHub landing pages

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/features#31]
For http://agu-binder.2i2c.cloud,  we want a customized landing page. The configuration for that hub includes the following:

```
binderhub:
  config:
    BinderHub:
      template_path: /etc/binderhub/custom/templates
      extra_static_path: /etc/binderhub/custom/static
      extra_static_url_prefix: /extra_static/
  initContainers:
    - name: git-clone-templates
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --branch=master
        - --depth=1
        - --
        - https://github.com/2i2c-org/agu-binder-custom-templates
        - /etc/binderhub/custom
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: custom-templates
          mountPath: /etc/binderhub/custom
  extraVolumes:
    - name: custom-templates
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-templates
      mountPath: /etc/binderhub/custom
```

My expectation is that by pushing changes to https://github.com/2i2c-org/agu-binder-custom-templates that should cause a change to the landing page visible at http://agu-binder.2i2c.cloud.

I assume I need to do *something* with `deployer` to trigger the appropriate helm action so cause that the template repo to be cloned again so that this hub picks up the changes and visible at http://agu-binder.2i2c.cloud.

Trying 

```
deployer deploy 2i2c agu-binder
```

causes a `helm upgrade`

```
helm upgrade --install --create-namespace --wait --namespace=agu-binder agu-binder /home/jmunroe/2i2c-org/infrastructure/helm-charts/binderhub --values=/home/jmunroe/2i2c-org/infrastructure/config/clusters/2i2c/agu-binder.values.yaml --values=/tmp/tmpldq4skso
```

but apparently no change to http://agu-binder.2i2c.cloud. I assume this because there has been no change to the helm charts so nothing needs to be modified.

Question: how can can trigger helm to rebuild this pod so that the changes made in https://github.com/2i2c-org/agu-binder-custom-templates get picked up?
